---
version: "3"
services:

  influxdb:
    image: influxdb
    container_name: influxdb_test
    environment:
      - UID=1000
      - GID=1000
      - INFLUXDB_DATA_QUERY_LOG_ENABLED=false
      - INFLUXDB_GRAPHITE_ENABLED=true
      - INFLUXDB_REPORTING_DISABLED=true
      - INFLUXDB_DB=testdb
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=supersecretpassword
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=secretpassword
    volumes:
      - ./etc/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ./var/lib/influxdb:/var/lib/influxdb
    ports:
      - 8086:8086
      - 2003:2003
    restart: unless-stopped

  telegraf:
    image: telegraf
    container_name: telegraf_test
    environment:
      - UID=1000
      - GID=1000
      - HOST_PROC=/host/proc
    volumes:
      - ./etc/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /proc:/host/proc:ro
    depends_on:
      - influxdb
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana_test
    environment:
      - UID=1000
      - GID=1000
    ports:
      - 3000:3000
    depends_on:
      - influxdb
    restart: unless-stopped
