---
version: '3'
services:

  influxdb:
    image: influxdb:1.8
    container_name: fh_influxdb
    environment:
      - INFLUXDB_REPORTING_DISABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminsecretpassword
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=telegrafsecretpassword
    volumes:
      # Mount for influxdb data directory
      - timedata:/var/lib/influxdb
      # Mount for influxdb configuration
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      # Mount for first-init scripts
      - ./influxdb/entrypoint/:/docker-entrypoint-initdb.d:ro
    ports:
      # The API for InfluxDB is served on port 8086
      - "8086:8086"
      # UDP Port
      - "8089:8089/udp"

  telegraf:
    image: telegraf
    container_name: fh_telegraf
    environment:
      - HOST_PROC=/host/proc
    volumes:
      # Mount for telegraf configuration
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      # Mount for proc access from host
      - /proc:/host/proc:ro
      # Mount for Docker API access
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8094:8094/udp"
    links:
      - influxdb
    depends_on:
      - influxdb

  chronograf:
    image: chronograf
    container_name: fh_chronograf
    environment:
      - REPORTING_DISABLED=true
    volumes:
      - chronodata:/var/lib/chronograf
    ports:
      - "8888:8888"
    links:
      - influxdb
    depends_on:
      - influxdb
      - telegraf

  proxy:
    build: proxy/
    image: fabiomix/forza-udp-proxy:1.0
    container_name: fh_proxy
    # command: --verbose --test
    ports:
      - "9999:9999/udp"
    links:
      - telegraf
    depends_on:
      - telegraf

volumes:
  timedata:
  chronodata:
