---
version: '3'
services:

  influxdb:
    image: influxdb:1.8
    container_name: fh_influxdb
    environment:
      - INFLUXDB_REPORTING_DISABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminsecretpassword
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=telegrafsecretpassword
    volumes:
      # Mount for influxdb data directory
      - timedata:/var/lib/influxdb
      # Mount for influxdb configuration
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      # Mount for first-init scripts
      - ./influxdb/entrypoint/:/docker-entrypoint-initdb.d:ro
    ports:
      # The API for InfluxDB is served on port 8086
      - "8086:8086"
      # UDP Port
      - "8089:8089/udp"

  telegraf:
    image: telegraf
    container_name: fh_telegraf
    environment:
      - HOST_PROC=/host/proc
    volumes:
      # Mount for telegraf configuration
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      # Mount for proc access from host
      - /proc:/host/proc:ro
      # Mount for Docker API access
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8094:8094/udp"
    links:
      - influxdb
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana
    container_name: fh_grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=passw0rd
      - GF_USERS_DEFAULT_THEME=dark
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=500ms
    volumes:
      - grdata:/var/lib/grafana
    ports:
      - "3000:3000"
    links:
      - influxdb
    depends_on:
      - influxdb
      - telegraf

  proxy:
    build: proxy/
    image: fabiomix/forza-udp-proxy:1.0
    container_name: fh_proxy
    # command: --verbose --test
    ports:
      - "9999:9999/udp"
    links:
      - telegraf
    depends_on:
      - telegraf

volumes:
  timedata:
  grdata:
